//ERROR
export const BARBER_NOT_EXIST_ERROR = "Barber does not exist"
export const BARBER_EXISTS_ERROR = "Barber already exists"
export const SELECT_SERVICE_ERROR = "Please select a service"
export const NO_BARBERS_ERROR = "No barbers available"
export const BARBER_CLOCKIN_ERROR = "Unable to change online status as you are currently clocked out"
export const NO_BARBER_SERVICEID_ERROR = "No barbers found for the given serviceId"
export const BARBER_NOT_APPROVE_ERROR = "Barber is not approved"
export const CUSTOMERS_IN_QUEUE_ERROR = "Cant clock you out as you have customers in the queue"
export const EMPTY_SERVICE_ERROR = "Please provide a service"

//SUCCESS
export const SIGNIN_SUCCESS = "Barber logged in successfully"
export const SIGNUP_SUCCESS = "Barber registered successfully"
export const LOGOUT_SUCCESS = "Barber logout successfully"
export const UPDATE_BARBER_SUCCESS = "Barber updated successfully"
export const BARBER_CONNECT_SALON_SUCCESS = "Your request has been sent for approval. Please wait..."
export const GET_ALL_BARBER_SUCCESS = "All barbers retrieved successfully"
export const CHANGE_BARBER_ONLINE_SUCCESS = "Barber online status changed successfully"
export const BARBER_SERVICES_SUCCESS = "Barber services retrieve successfully"
export const BARBER_DETAILS_SUCCESS = "Barber retrive successfully"
export const BARBER_CLOCKIN_SUCCESS = "You are clocked in"
export const BARBER_CLOCKOUT_SUCCESS = "You are clocked out"
export const CHANGE_PASSWORD_SUCCESS = "Barber password updated successfully"
export const CREATE_BARBER_SUCCESS = "Barber created successfully" 